# Generated by Django 3.1.2 on 2020-10-24 21:40

from django.db import migrations
import uuid

def generate_dummy_data(apps, schema_editor):

    Image = apps.get_model('api', 'Image')

    for x in range(5000):
        img = Image(device_id=uuid.uuid4().hex[:6].upper(), image_binary=uuid.uuid4().hex.upper().encode('utf-8'))
        img.save()

class Migration(migrations.Migration):


    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_dummy_data),
    ]
